### ISSUE TITLE
HCFEssentials is compatible with DrtShockHCF?

### ISSUE THREAD

**Issue by iOxf** [ItsMonkeyyy/HCFE-Issues#1]
i buy the last version of drtshock hcf b59, and have problem with the plugin of ItsMonkey , the scoreboard of HCFEssentials, removes colors tab, try everything but when threw a enderpearl colors come out when it is replaced by the Scoreboard HCFEssentials :'/, http://imgur.com/qirUSLD

**Comment by ItsMonkeyyy** [comment]
//English
This will be fixed soon, already started writing up a new Scoreboard class. An update will be released soon :)

//Español
Esto sera arreglado pronto. Ya estoy escribiendo una clase nueva para el Scoreboard. Un update va a salir pronto :)

**Comment by iOxf** [comment]
Muy bien!

**Comment by StaticCraft** [comment]
Hello I am currently having a problem with this plugin as it is not showing me the scoreboard

**Comment by ItsMonkeyyy** [comment]
That is because you have a leaked version of HCFEssentials. Anyways, with drtshock's newest update to HCFactions the scoreboard will work. If you got that plugin leaked as well then you're out of luck.
